<?php
$lang = array(

// Required for MODULES page

'ct_admin_module_name'    => 'CT Admin',
'ct_admin_module_description' => 'Bestellungs- und Kundenverwaltung für CartThrob Stores.',

//----------------------------------------

// Additional Key => Value pairs go here

// END
'dashboard' => 'Dashboard',
'cartthrob_not_setup' => 'CartThrob wurde noch nicht konfiguriert. Bitte beenden Sie die CartThrob-Konfiguration, bevor es weiter gehen kann ...',
'record_added' => 'Eintrag hinzugefügt',
'order_id' => 'Bestellnummer',
'customer_name' => 'Kundenname',
'order_date' => 'Bestelldatum',
'no_matching_orders' => 'Keine Bestellungen gefunden',
'orders' => 'Bestellungen',
'order_view' => 'Bestellübersicht',
'order_details' => 'Details zur Bestellung',
'customers' => 'Kunden',
'customer_view' => 'Kundenübersicht',
'delete_selected' => 'Ausgewählte löschen',
'edit_selected' => 'Ausgewählte bearbeiten',
'billing_address' => 'Rechnungsadresse',
'products' => 'Produkte',
'order_not_found' => 'Bestellung nicht gefunden',
'delete_order_confirm' => 'Sind Sie sicher, dass Sie diese Bestellungen löschen möchten?',
'delete_product_confirm' => 'Sind Sie sicher, dass Sie diese Produkte löschen möchten?',
'product_sub_warning' => 'Mal ernsthaft, sind Sie wirklich sicher? Dieser Schritt entfernt <em>alle</em> Kunden- und Bestelldaten unwiderruflich.',
'orders_deleted' => 'Bestellungen gelöscht',
'orders_delete_failure' => 'Die Bestellungen konnten nicht gelöscht werden...',
'order_transaction_id' => 'Transaktionsnummer',
'order_shipping' => 'Versand',
'order_tax' => 'Steuer',
'quantity' => 'Menge',
'unit_price' => 'Stückpreis',
'product' => 'Produkt',
'order_coupons' => 'Coupons',
'order_shipping_option' => 'Versandoptionen',
'order_discount' => 'Rabatt',
'country_code' => 'Länderkennung',
'order_not_updated' => 'Die Bestellung konnte nicht aktualisiert werden',
'order_updated' => 'Bestellung aktualisiert!',
'reports' => 'Statistiken',
'product_sum_report' => 'Statistik: Produkte',
'nothing_to_report' => 'Keine Daten verfügbar...',
'summary_report' => 'Zusammenfassung',
'current_day_total' => 'Heute',
'current_month_total' => 'Bestellungen in diesem Monat',
'current_year_total' => 'Bestellungen in diesem Jahr',
'monthly_history_report' => 'Monatliche Gesamtübersicht',
'low_stock_report' => 'Lagerbestand',
'update_and_finished' => 'Aktualisiert und beendet',
'open' => 'Offen',
'total_sales' => 'Gesamt: Verkäufe',
'total_orders' => 'Gesamt: Bestellungen',
'customer_details' => 'Kundendaten',
'email' => 'E-Mail-Adresse',
'customers_orders' => 'Bestellungen des Kunden',
'customers_products' => 'Bestellte Artikel',
'first_order' => 'Erste Bestellung',
'last_order' => 'Letzte Bestellung',
'total_amount_spent' => 'Gesamtausgaben',
'open' => 'offen',
'closed' => 'geschlossen',
'order_total' => 'Gesamtbetrag',
'customer_address' => 'Kundenadresse',
'export_failed' => 'Export fehlgeschlagen',
'export' => 'Export',

'configure_ct_admin' => 'CT Admin konfigurieren',
'configure' => 'Konfigurieren',
'license_number' => 'Lizenznummer',
'missing_license_number' => 'Bitten geben Sie Ihre Lizenznummer ein. <a href="#config_url#" target="_parent">Lizenznummer eingeben</a> oder <a href="http://devot-ee.com/add-ons/ct-admin/" target="_blank">Lizenz erwerben</a>',
'allowed_access_levels' => 'Zugriffsrechte',
'allowed_access_levels_instructions' => 'Standardmäßig gewährt CT Admin nur Administratoren den Zugriff auf Einstellungen. Wenn Sie anderen Benutzergruppen den Zugriff gestatten möchten, wählen Sie diese aus der Liste.',
'settings_updated' => 'Einstellungen aktualisiert',
'settings_update_fail' => 'Die Einstellungen konnten nicht aktualisiert werden!',

'this_years_sales' => 'Verkäufe in diesem Jahr',
'this_years_orders' => 'Bestellungen in diesem Jahr',
'total_customers' => 'Gesamtanzahl: Kunden',
'total_products' => 'Gesamtanzahl: Produkte',
'todays_orders' => 'Bestellungen: Heutige',
'average_order' => 'Bestellungen: Durchschnitt',
'this_months_orders' => 'Bestellungen: in diesem Monat',
'recent_sales' => 'Kürzlich abgeschlossene Verkäufe',
'store_overview' => 'Übersicht',

'export_date_format' => 'Export: Datumsformat',
'export_date_format_instructions' => 'Das Format des Datums beim Export von Daten aus CT Admin. Achten Sie darauf, dass das Format den <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">Format-Optionen von ExpressionEngine</a> entspricht.',
'no_customers' => 'Keine Kunden gefunden',
'nav_ct_admin' => 'CT Admin Einstellungen',

'ct_date_format' => 'Format: Datum',
'ct_date_format_instructions' => 'Welches Format soll CT Admin im ExpressionEngine Control Panel für das Datum verwenden? Achten Sie darauf, dass das Format den <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">Format-Optionen von ExpressionEngine</a> entspricht.',

'orders_list_limit' => 'Limit: Bestellungen',
'orders_list_limit_instructions' => 'Wie viele Bestellungen sollen in der Bestellübersicht angezeigt werden?',
'cust_list_limit' => 'Limit: Kunden',
'cust_list_limit_instructions' => 'Wie viele Kunden sollen in der Kundenübersicht angezeigt werden?',
'order_graph_limit' => 'Limit: Bestell-Diagramm',
'order_graph_limit_instructions' => 'Wie viele Tage soll das Diagramm im Dashboard anzeigen?',
'graph_date_format' => 'Datumsformat des Diagramms',
'graph_date_format_instructions' => 'Das Format des Datums beim Anzeigen der Verkaufshistorie. Achten Sie darauf, dass das Format den <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">Format-Optionen von ExpressionEngine</a> entspricht.',

'print_invoice' => 'Rechnung drucken',
'packing_slip' => 'Packzettel',
'success_statuses' => 'Erfolg Status',
'success_statuses_instructions' => 'Welche Status möchten Sie als Erfolg verzeichnen? Die gewählten Status dienen als Grundlage für die Berechnung von erfolgreich abgeschlossenen Bestellungen.',
'activity_for' => 'Aktivität ',

'details' => 'Details',
'sales' => 'Verkäufe',
'filter_by_status' => 'Nach Status filtern',

'date_range' => 'Zeitraum',
'past_day' => 'Gestern',
'past_week' => 'Letzte Woche',
'past_month' => 'Letzter Monat',
'past_six_months' => 'Letzte 6 Monate',
'past_year' => 'Letztes Jahr',
'any_date' => 'Insgesamt',

'keywords' => 'Schlüsselbegriffe',
'results' => 'Ergebnisse',
'end_date' => 'Abschlussdatum',
'start_date' => 'Anfangsdatum',

'total_range' => 'Gesamter Bereich',
'select_range' => 'Gewählter Bereich',
'sales_range' => 'Bereich: Verkäufe',

// 'order_country_report' => 'Order to Country Report',
'date_formats' => 'Datumsformate',
'limits' => 'Limits',
'templates' => 'Vorlagen',
'global_settings' => 'Globale Einstellungen',

'packingslip_template_url' => 'Eigene URL für Packzettel',
'packingslip_template_url_instructions' => 'Wenn Sie einen eigenen Packzettel verwenden möchten, geben Sie dessen Adresse hier an. Beachten Sie, dass die $entry_id der Bestellung der URL angehängt wird.',
'invoice_template_url' => 'Eigene URL für Rechnungen',
'invoice_template_url_instructions' => 'Ähnlich wie beim Packzettel; geben Sie einfach die URL - oder den Pfad - zur eigenen Rechnungsvorlage an. Beachten Sie auch hier, dass die $entry_id der Bestellung der URL angehängt wird.',
'reporting_options' => 'Einstellungen Statistiken',
'country_field' => 'Länderfeld',
'ip_to_location_module' => 'IP-to-Location-Modul',
'inventory_report_enable' => 'Statistik zum Lagerbestand aktivieren',
'inventory_report_enable_instructions' => 'Nicht jeder Laden pflegt seinen Lagerbestand. Um mögliche Verwirrung zu vermeiden, entfernen Sie das Häkchen, um die Statistik nicht anzuzeigen',
'country_report_data' => 'Geochart Datenquelle',
'country_report_data_instructions' => 'Wenn Sie beim Checkout keine Ortsdaten erfassen, können Sie die IP-Adresse des Kunden nutzen, um seinen Standort zu bestimmen. ABER VORSICHT: um diese Funktion zu nutzen muss das IP-to-Location-Modul installiert sein, was sehr rechenintensiv sein kann!',
'edit_in_publish_view' => 'In Publish View editieren',

'print_invoices' => 'Rechnungen drucken',
'change_status' => 'Status ändern',
'first_purchase' => 'Erster Kauf',
'last_purchase' => 'Letzter Kauf',
'change_status_question' => 'Sind Sie sicher, dass Sie den Status der unten stehenden Bestellungen auf "#status#" ändern möchten?',
'override_cp_order_edit_routing' => 'CP-Routing für Bestellungsänderungen forcieren?',
'override_cp_order_edit_routing_instructions' => 'Standardmäßig werden alle Änderungen an Bestellungen, die über das Control Panel gestartet werden, an CT Admin weitergeleitet. Entfernen Sie das Häkchen, um dies zu unterbinden.',
'override_cp_product_edit_routing' => 'CP-Routing für Produktänderungen forcieren?',
'override_cp_product_edit_routing_instructions' => 'Standardmäßig werden alle Änderungen an Produkten, die über das Control Panel gestartet werden, an CT Admin weitergeleitet. Entfernen Sie das Häkchen, um dies zu unterbinden.',
'latest_orders' => 'Letzte Bestellungen',
'latest_orders_limit' => 'Limit: Letzte Bestellungen',
'latest_orders_limit_instructions' => 'Wie viele Tage soll das Modul für "Letzte Bestellungen" im Dashboard anzeigen?',

'product_updated' => 'Produkt aktualisiert',
'product_title' => 'Produktname',
'product_not_found' => 'Produkt nicht gefunden',
'total_sold' => 'Verkäufe insgesamt',
'creation_date' => 'Erstelldatum',
'products_list_limit' => 'Limit: Produktübersicht',
'products_list_limit_instructions' => 'Wie viele Produkte möchten Sie in der Produktübersicht anzeigen?',
'no_matching_products' => 'Keine Produkte gefunden',
'top' => 'Top',
'abandoned_cart_report' => 'Statistik: vergessene Warenkörbe',
'require_valid_coupon' => 'Nur gültige Coupons zulassen',
'require_valid_coupon_instructions' => 'Wenn aktiviert, wird jeder Coupon-Code auf Gültigkeit überprüft. Bei Bestellungen werden dann nur gültige Coupons zugelassen. Wenn kein Coupon-Code eingegeben wird, hat diese Einstellung keine Auswirkung.',
'please_enter_valid_coupon' => 'Bitte geben Sie einen gültigen Coupon-Code ein',
''=>''
);