<?php
$lang = array(

// Required for MODULES page

'ct_admin_module_name'		=> 'CT Admin',
'ct_admin_module_description'	=> 'Creates a stand alone interface for viewing orders and customers for a CartThrob store. ',

//----------------------------------------

// Additional Key => Value pairs go here

// END
'dashboard' => 'Dashboard',
'cartthrob_not_setup' => 'CartThrob isn\'t set up yet. Please finish setting CartThrob up before continuing...',
'record_added' => 'Record Added',
'order_id' => 'Order ID',
'customer_name' => 'Customer Name',
'order_date' => 'Order Date',
'no_matching_orders' => 'No Orders Found',
'orders' => 'Orders',
'order_view' => 'Order View',
'order_details' => 'Order Details',
'customers' => 'Customers',
'customer_view' => 'Customer View',
'delete_selected' => 'Delete Selected',
'edit_selected' => 'Edit Selected',
'billing_address' => 'Billing Address',
'products' => 'Products',
'order_not_found' => 'Order Not Found',
'delete_order_confirm' => 'Are you sure you want to delete these orders?',
'delete_product_confirm' => 'Are you sure you want to delete these products?',
'product_sub_warning' => 'Seriously, are you sure? This will remove Order and Customer data so you should be <em>really</em> sure you want to do this.',
'orders_deleted' => 'Orders Deleted',
'orders_delete_failure' => 'Coudn\'t delete orders...',
'order_transaction_id' => 'Order Transaction ID',
'order_shipping' => 'Shipping',
'order_tax' => 'Tax',
'quantity' => 'Quantity',
'unit_price' => 'Unit Price',
'product' => 'Product',
'order_coupons' => 'Coupons',
'order_shipping_option' => 'Shipping Options',
'order_discount' => 'Discount',
'country_code' => 'Country Code',
'order_not_updated' => 'You\'re order couldn\'t be updated...',
'order_updated' => 'Order Updated!',
'reports' => 'Reports',
'product_sum_report' => 'Product Sum Report',
'nothing_to_report' => 'Nothing to report...',
'summary_report' => 'Summary Report',
'current_day_total' => 'Today',
'current_month_total' => 'Orders This Month',
'current_year_total' => 'Orders This Year',
'monthly_history_report' => 'Monthly History Report',
'low_stock_report' => 'Inventory Report',
'update_and_finished' => 'Update and Finished',
'open' => 'Open',
'total_sales' => 'Total Sales',
'total_orders' => 'Total Orders',
'customer_details' => 'Customer Details',
'email' => 'Email Address',
'customers_orders' => 'Customers Orders',
'customers_products' => 'Customer Products',
'first_order' => 'First Order',
'last_order' => 'Last Order',
'total_amount_spent' => 'Total Amount Spent',
'open' => 'Open',
'closed' => 'Closed',
'order_total' => 'Order Total',
'customer_address' => 'Customer Address',
'export_failed' => 'Export Failed',
'export' => 'Export',

'configure_ct_admin' => 'Configure CT Admin',
'configure' => 'Configure',
'license_number' => 'License Number',
'missing_license_number' => 'Please enter your license number. <a href="#config_url#" target="_parent">Enter License</a> or <a href="http://devot-ee.com/add-ons/ct-admin/" target="_blank">Buy A License</a>',
'allowed_access_levels' => 'Allowed Access Levels',
'allowed_access_levels_instructions' => 'CT Admin will initially only allow Super Admins access to the settings but if you need to allow other groups select them from the list.',
'settings_updated' => 'Settings Updated',
'settings_update_fail' => 'Couldn\'t Update Settings',

'this_years_sales' => 'Sales This Year',
'this_years_orders' => 'Orders This Year',
'total_customers' => 'Total Customers',
'total_products' => 'Total Products',
'todays_orders' => 'Today\'s Orders',
'average_order' => 'Average Order',
'this_months_orders' => 'This Month\'s Orders',
'recent_sales' => 'Recent Sales',
'store_overview' => 'Overview',
'export_date_format' => 'Export Date Format',
'export_date_format_instructions' => 'The date format you want CT Admin to use when exporting data. Note that the format should conform to the <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">ExpressionEngine date format</a>.',
'no_customers' => 'No Customers Found',
'nav_ct_admin' => 'Ct Admin Settings',

'ct_date_format' => 'Date Format',
'ct_date_format_instructions' => 'The date format you want CT Admin to use when displaying data within the ExpressionEngine Control Panel. Note that the format should conform to the <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">ExpressionEngine date format</a>.',

'orders_list_limit' => 'Order List Limit',
'orders_list_limit_instructions' => 'How many items do you want to list on the Order List page?',
'cust_list_limit' => 'Customer List Limit',
'cust_list_limit_instructions' => 'How many items do you want to list on the Customer List page?',
'order_graph_limit' => 'Order Graph Limit',
'order_graph_limit_instructions' => 'How many days do you want to display on the Dashboard graph?',
'graph_date_format' => 'Graph Date Format',
'graph_date_format_instructions' => 'The date format you want CT Admin to use when displaying data within the Dashboard order history graph. Note that the format should conform to the <a href="http://expressionengine.com/user_guide/templates/date_variable_formatting.html#date-formatting-codes" target="_blank">ExpressionEngine date format</a>.',

'print_invoice' => 'Print Invoice',
'packing_slip' => 'Packing Slip',
'success_statuses' => 'Success Statuses',
'success_statuses_instructions' => 'What statuses do you consider being a success? The selected statuses will be used for calculating successful orders.',
'activity_for' => 'Activity For ',

'details' => 'Details',
'sales' => 'Sales',
'filter_by_status' => 'Filter by Status',

'date_range' => 'Date Range',
'past_day' => 'Past Day',
'past_week' => 'Past Week',
'past_month' => 'Past Month',
'past_six_months' => 'Past 6 Months',
'past_year' => 'Past Year',
'any_date' => 'Any Date Range',

'keywords' => 'Keywords',
'results' => 'Results',
'end_date' => 'End Date',
'start_date' => 'Start Date',

'total_range' => 'Total Range',
'select_range' => 'Select Range',
'sales_range' => 'Sales Range',

'order_country_report' => 'Order to Country Report',
'date_formats' => 'Date Formats',
'limits' => 'Limits',
'templates' => 'Templates',
'global_settings' => 'Global Settings',
		
'packingslip_template_url' => 'Custom Packing Slip URL',
'packingslip_template_url_instructions' => 'If you create a custom packing slip you can configure CT Admin to use that instead of the default slip. Note that the $entry_id for the order is appended to the URL entered here.',
'invoice_template_url' => 'Custom Invoice URL',
'invoice_template_url_instructions' => 'Similiar to Custom Packing Slip URL; just enter the URL (or path) to use. Note that the $entry_id for the order is appended to the URL entered here.',
'reporting_options' => 'Reporting Options',
'country_field' => 'Country Field', 
'ip_to_location_module' => 'Ip To Location Module',
'inventory_report_enable' => 'Enable Inventory Report',	
'inventory_report_enable_instructions' => 'Some stores don\'t carry an inventory so this report could cause confusion or just plain get in the way. To remove just uncheck.',		
'country_report_data' => 'Geochart Data Source',
'country_report_data_instructions' => 'Depending on how your store is set up you might not record countries as a part of the checkout process. If that\'s the case, you can set the country report to use IP addresses instead. BE WARNED: using IP to Locaiton requires the IP to Location module be installed and can be resource intensive.',
'edit_in_publish_view' => 'Edit In Publish View',
		
'print_invoices' => 'Print Invoices',
'change_status' => 'Change Status',
'first_purchase' => 'First Purchase',
'last_purchase' => 'Last Purchase',		
'change_status_question' => 'Are you sure you want to change the below order(s) status to "#status#"?',
'override_cp_order_edit_routing' => 'Override CP Order Edit Routing?',
'override_cp_order_edit_routing_instructions' => 'By default, CT Admin will route any edit of an order in the Control Panel to CT Admin. Uncheck to disable this.',		
'override_cp_product_edit_routing' => 'Override CP Product Edit Routing?',
'override_cp_product_edit_routing_instructions' => 'By default, CT Admin will route any edit of a product in the Control Panel to CT Admin. Uncheck to disable this.',			
'latest_orders' => 'Latest Orders',
'latest_orders_limit' => 'Latest Orders Limit',
'latest_orders_limit_instructions' => 'How many days do you want the Latest Orders widget on the Dashboard to use for pulling orders?',

'product_updated' => 'Product Updated',
'product_title' => 'Product Title',
'product_not_found' => 'Product Not Found',
'total_sold' => 'Total Sold',
'creation_date' => 'Creation Date',
'products_list_limit' => 'Product List Limit',
'products_list_limit_instructions' => 'How many items do you want to list on the Product List page?',
'no_matching_products' => 'No Products Found',
'top' => 'Top',
'abandoned_cart_report' => 'Abandoned Cart Report',
		
'require_valid_coupon' => 'Require Valid Coupons',
'require_valid_coupon_instructions' => 'If enabled, any order with a coupon code form will require a valid coupon code if one is entered. If no coupon code is entered then this is ignored.',
'please_enter_valid_coupon' => 'Please enter a valid coupon code',
''=>''
);